<?php
include '../includes/config.php';
require_once '../includes/lab_ui.php';
require_once '../includes/attack_config.php';
require_once '../includes/lab_state.php';

$categories = labCategories();
$attacks = attackScenarios();

if ($_SERVER['REQUEST_METHOD'] === 'POST' && ($_POST['export'] ?? '') === 'html') {
    $attack_id = $_POST['attack_id'] ?? '';
    if ($attack_id && attackScenario($attack_id)) {
        updateAttackProgress($attack_id, 'reported');
    }

    $title = $_POST['title'] ?? 'Pentest Finding';
    $category = $_POST['category'] ?? 'OWASP';
    $severity = $_POST['severity'] ?? 'Medium';
    $evidence = $_POST['evidence'] ?? '';
    $impact = $_POST['impact'] ?? '';
    $recommendation = $_POST['recommendation'] ?? '';

    header('Content-Type: text/html; charset=UTF-8');
    header('Content-Disposition: attachment; filename="pentest-finding.html"');
    echo '<!DOCTYPE html><html><head><meta charset="UTF-8"><title>' . e($title) . '</title>';
    echo '<style>body{font-family:Arial,sans-serif;line-height:1.6;margin:40px;color:#172033}h1{color:#10243f}.meta{display:grid;grid-template-columns:1fr 1fr;gap:12px}.box{border:1px solid #d9e4ef;border-radius:10px;padding:16px;margin:16px 0;background:#f8fbff}pre{white-space:pre-wrap}</style>';
    echo '</head><body>';
    echo '<h1>' . e($title) . '</h1>';
    echo '<div class="meta"><div class="box"><strong>Category</strong><br>' . e($category) . '</div><div class="box"><strong>Severity</strong><br>' . e($severity) . '</div></div>';
    echo '<div class="box"><h2>Evidence</h2><pre>' . e($evidence) . '</pre></div>';
    echo '<div class="box"><h2>Impact</h2><pre>' . e($impact) . '</pre></div>';
    echo '<div class="box"><h2>Recommendation</h2><pre>' . e($recommendation) . '</pre></div>';
    echo '<p>Generated by Modern School Portal OWASP Pentesting Simulation Lab.</p>';
    echo '</body></html>';
    exit();
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <?php renderLabHead('Report Builder'); ?>
</head>
<body>
    <header class="lab-header compact">
        <div class="container">
            <div class="lab-kicker">Evidence to Finding</div>
            <h1>Pentest Report Builder</h1>
            <p>Draft concise findings while practicing each intentionally vulnerable lab.</p>
        </div>
    </header>

    <?php renderLabNav(); ?>

    <main class="container page-shell">
        <section class="report-layout">
            <form method="POST" class="lab-panel">
                <h2>Finding Draft</h2>
                <div class="column-2">
                    <div class="form-group">
                        <label>Attack Scenario</label>
                        <select name="attack_id">
                            <option value="">General finding</option>
                            <?php foreach ($attacks as $id => $attack): ?>
                                <option value="<?php echo e($id); ?>"><?php echo e($attack['title']); ?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                    <div class="form-group">
                        <label>OWASP Category</label>
                        <select name="category">
                            <?php foreach ($categories as $id => $lab): ?>
                                <option><?php echo e($id . ' - ' . $lab['title']); ?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                    <div class="form-group">
                        <label>Severity</label>
                        <select name="severity">
                            <option>Critical</option>
                            <option>High</option>
                            <option>Medium</option>
                            <option>Low</option>
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <label>Title</label>
                    <input type="text" name="title" value="Unauthorized access to student records">
                </div>
                <div class="form-group">
                    <label>Evidence</label>
                    <textarea name="evidence" rows="7" placeholder="Payload, affected URL, observed result, and screenshot notes."></textarea>
                </div>
                <div class="form-group">
                    <label>Impact</label>
                    <textarea name="impact" rows="5" placeholder="Explain business impact in school portal terms."></textarea>
                </div>
                <div class="form-group">
                    <label>Recommendation</label>
                    <textarea name="recommendation" rows="5" placeholder="Describe the secure design without removing the lab exercise."></textarea>
                </div>
                <button type="submit" name="export" value="html" class="btn-primary">Export HTML Finding</button>
            </form>

            <aside class="lab-panel">
                <h2>Evidence Checklist</h2>
                <div class="check-grid vertical">
                    <label><input type="checkbox"> Target URL recorded</label>
                    <label><input type="checkbox"> Payload recorded</label>
                    <label><input type="checkbox"> Before state captured</label>
                    <label><input type="checkbox"> After state captured</label>
                    <label><input type="checkbox"> OWASP category mapped</label>
                    <label><input type="checkbox"> Remediation written</label>
                </div>
            </aside>
        </section>
    </main>

    <footer>
        <p>&copy; 2026 Modern School Portal | Pentest report practice</p>
    </footer>
</body>
</html>
